CREATE DATABASE inlock_games_tarde;
GO


USE inlock_games_tarde;
GO

CREATE TABLE ESTUDIO (
	idEstudio TINYINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	nomeEstudio VARCHAR(200) NOT NULL
);
GO

CREATE TABLE JOGO (
	idJogo TINYINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	nomeJogo VARCHAR(200) NOT NULL,
	descricao VARCHAR(1000) NOT NULL,
	dataLancamento DATE NOT NULL,
	valor SMALLMONEY NOT NULL,
	idEstudio TINYINT FOREIGN KEY REFERENCES ESTUDIO(idEstudio) NOT NULL
);
GO

CREATE TABLE TIPOUSUARIO (
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	titulo VARCHAR(13) NOT NULL
);
GO

CREATE TABLE USUARIO (
	idUsuario TINYINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	email VARCHAR(256) NOT NULL,
	senha VARCHAR(200) NOT NULL,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario) NOT NULL
);
GO